# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SystemPreferenceDemo' do

pod "YYModel"
pod 'Masonry'

end

target 'SystemPreference' do

pod "YYModel"
pod 'Masonry'

end

